#![feature(proc_macro_quote)]
//!
//! Convenience **attribute procedural macro** for defining expression
//! languages and recursive ASTs suitable for use in equivalence graphs.
//!

use std::iter::Peekable;

use proc_macro::{Delimiter, Ident, Span, TokenStream, TokenTree, quote};

fn match_punct(tt: Option<&TokenTree>, char: char) -> bool {
  if let Some(TokenTree::Punct(p)) = tt {
    p.as_char() == char
  } else {
    false
  }
}

fn parse_attrs<T>(source: &mut Peekable<T>) -> Option<TokenStream>
where
  T: Iterator<Item = TokenTree>,
{
  /*
  https://doc.rust-lang.org/reference/attributes.html
  OuterAttribute →
    # [ Attr ]
  */
  let mut attrs_tt = Vec::new();
  while match_punct(source.peek(), '#') {
    attrs_tt.push(source.next()?); // consume '#'
    if let Some(attr) = source.next() // consume [ Attr ]
      && let TokenTree::Group(_) = attr
    {
      attrs_tt.push(attr);
    } else {
      return None;
    }
  }

  Some(TokenStream::from_iter(
    attrs_tt, // check macro position
  ))
}

fn parse_vis<T>(source: &mut Peekable<T>) -> Option<TokenStream>
where
  T: Iterator<Item = TokenTree>,
{
  /*
  https://doc.rust-lang.org/reference/visibility-and-privacy.html
  Visibility →
      pub
    | pub ( crate )
    | pub ( self )
    | pub ( super )
    | pub ( in SimplePath )
  */
  let mut vis_tt = Vec::new();
  if let Some(TokenTree::Ident(ident)) = source.peek()
    && ident.to_string() == "pub"
  {
    vis_tt.push(source.next()?); // consume "pub"
    if let Some(TokenTree::Group(group)) = source.peek()
      && group.delimiter() == Delimiter::Parenthesis
    {
      vis_tt.push(source.next()?); // consume (...)
    }
  }

  Some(TokenStream::from_iter(
    vis_tt, // empty if private
  ))
}

fn parse_enum_name<T>(source: &mut T) -> Option<Ident>
where
  T: Iterator<Item = TokenTree>,
{
  /*
  https://doc.rust-lang.org/reference/items/enumerations.html
  Enumeration →
    enum IDENTIFIER GenericParams? WhereClause? { EnumVariants? }
  */

  if let Some(TokenTree::Ident(ident)) = source.next()
    && ident.to_string() == "enum"
    && let Some(TokenTree::Ident(enum_name)) = source.next()
  {
    Some(enum_name)
  } else {
    None
  }
}

fn parse_attr_name(attr: TokenStream) -> Option<Ident> {
  /*
  AttrName →
    expr_impl ( IDENTIFIER )
  */
  let mut attr = attr.into_iter();
  if let Some(TokenTree::Ident(target_name)) = attr.next() {
    attr.next().map_or(Some(target_name), |_| None)
  } else {
    None
  }
}

/// Generate a recursive AST and conveniences required by the `Type` trait.
/// This attribute macro is intended to be applied to a *generic enum*
/// representing a tree-shaped expression language.
///
/// ---
///
/// ## Generated items
///
/// Given:
///
/// ```rust
/// #[expr_impl(Name)]
/// enum Enum<T> { ... }
/// ```
///
/// The macro generates:
///
/// | Item | Description |
/// |-----|-------------|
/// | `struct Name(Box<NameEnum>)` | Recursive heap-allocated wrapper |
/// | `type NameEnum = Enum<Name>` | Recursive enum alias |
/// | `From<NameEnum> for Name`    | Lift enum into boxed form (forward) |
/// | `Into<NameEnum> for Name`    | Unwrap boxed form (backward) |
/// | `AsRef<NameEnum> for Name`   | Borrow underlying enum |
///
/// The generated items preserve the visibility and attributes of the original enum.
///
/// ## Required
///
/// - The attribute must contain **exactly one identifier**
/// - The macro may only be applied to an `enum`
/// - The enum must be **generic over its recursive parameter**
///
/// **Note:** The [`From`] and [`Into`] traits are required when implementing the
/// `Type` trait but can be implemented manually in specific contexts.
/// Invalid usages of this macro result in a compile-time error.
///
#[proc_macro_attribute]
pub fn expr_impl(attr: TokenStream, mut item: TokenStream) -> TokenStream {
  let attr_name = parse_attr_name(attr).expect(
    "`expr_impl` requires a single attribute name, e.g. `#[expr_impl(Name)]`", // macro dependent
  );

  let mut item_iter = item.clone().into_iter().peekable();

  let attrs = parse_attrs(&mut item_iter).unwrap(); // compiler dependent
  let vis = parse_vis(&mut item_iter).unwrap(); // compiler dependent
  let enum_name = parse_enum_name(&mut item_iter).expect(
    "`impl_expr` can only be applied on `enum`s", // macro dependent
  );

  let rec_ty_name = Ident::new(
    // Recursive type definition: {attr_name}{enum_name}.
    &format!("{}{}", attr_name, enum_name),
    Span::call_site(),
  );

  item.extend(quote! {
    /// A recursive struct with pointer-based nodes [generated by `expr_impl`].
    $attrs
    $vis struct $attr_name(Box<$rec_ty_name>);

    /// A recursive tree expression [generated by `expr_impl`].
    $vis type $rec_ty_name = $enum_name<$attr_name>;

    impl ::std::convert::From<$rec_ty_name> for $attr_name {
      #[inline]
      fn from(expr: $rec_ty_name) -> Self {
        // Conversion (bwd)
        // recursive enum → recursive struct
        $attr_name(Box::new(expr))
      }
    }

    impl ::std::convert::Into<$rec_ty_name> for $attr_name {
      #[inline]
      fn into(self) -> $rec_ty_name {
        // Conversion (fwd)
        // recursive struct → recursive enum
        *(self.0)
      }
    }

    impl ::std::convert::AsRef<$rec_ty_name> for $attr_name {
      #[inline]
      fn as_ref(&self) -> &$rec_ty_name {
        // Reference
        // recursive struct → &recursive enum
        &(self.0)
      }
    }
  });
  item
}
